CREATE TABLE IF NOT EXISTS STATUS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL CHECK (NAME IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS SUBSCRIPTION (
    ID VARCHAR(255) PRIMARY KEY,
    STATUS_ID INT,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID)
);


CREATE TABLE IF NOT EXISTS public.EVENT_HISTORY (
    ID SERIAL PRIMARY KEY,
    TYPE VARCHAR(255),
    SUBSCRIPTION_ID VARCHAR(255),
    CREATED_AT TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION(ID)
);